language: node_js
os:
- linuxdist: trusty
sudo: required
addons:
 chrome: stable
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
# before_script:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3 # give xvfb some time to start
node_js:
  # - node
  - 8
